import Layout from "@/components/layout/Layout";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tiger TKD Omega",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="https://tigers-tkd-omega.s3.amazonaws.com/logo.png"
        />
      </head>
      <body className={inter.className}>
        {/* <script
          src="https://kit.fontawesome.com/db311df611.js"
          crossOrigin="anonymous"
        /> */}
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
